run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocritic
    - gofmt
    - goimports
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G104 # Duplicated errcheck
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
